basePath: /
definitions:
  controllers.errorResponse:
    properties:
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API Server for CRUD Application
  title: CRUD Application
  version: "1.2"
paths:
  /api/blogs:
    get:
      description: get blog by id
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/controllers.errorResponse'
      summary: GetBlog
      tags:
      - api
  /login-verification:
    post:
      parameters:
      - description: Account ID
        in: path
        name: login
        required: true
        type: string
      - description: Password
        in: path
        name: password
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/controllers.errorResponse'
  /register:
    post:
      description: get blog by id
      parameters:
      - description: Account ID
        in: path
        name: login
        required: true
        type: string
      - description: Password
        in: path
        name: password
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/controllers.errorResponse'
      summary: GetBlog
swagger: "2.0"
